#!/bin/sh

time=`date +%s`
suff=-${time}.bkp

mkdir backup -p

# bashrc
cp /home/sika/.bashrc backup/.bashrc$suff
rm /home/sika/.bashrc
cp data/bashrc /home/sika/.bashrc
chown sika:sika /home/sika/.bashrc

# c
cp data/c /usr/local/bin/c

# i3
cp /etc/i3/config backup/i3$suff
rm /etc/i3/config
cp data/i3 /etc/i3/config

# tmux
cp /etc/tmux.conf backup/tmux.conf$suff
rm /etc/tmux.conf
cp data/tmux.conf /etc/tmux.conf

# vimrc
cp /etc/vim/vimrc backup/vimrc$suff
rm /etc/vim/vimrc
cp data/vimrc /etc/vim/vimrc

# xrandr2
cp /usr/local/bin/xrandr2 backup/xrandr2$suff
rm /usr/local/bin/xrandr2
cp data/xrandr2 /usr/local/bin/xrandr2

