#!/bin/sh

if [ "$1" = "home" ]
then
    xrandr --auto --output LVDS1 --mode 1366x768 --output HDMI1 --mode 1280x1024 --right-of LVDS1
elif [ "$1" = "vadrax2" ]
then
    xrandr --auto --output LVDS1 --mode 1366x768 --output HDMI1 --mode 1920x1200 --above LVDS1
elif [ "$1" = "vadrax" ]
then
    xrandr --auto --output LVDS1 --mode 1366x768 --output HDMI1 --mode 1920x1080 --above LVDS1
else
    xrandr --auto
fi
