# barshrc
# Ondrej Sika <ondrej@ondrejsika.com>
#####################################

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
export EDITOR=/usr/bin/vim

export PATH=$PATH:/home/sika/bin

alias cc="xclip -sel clip"

alias serve="python -m SimpleHTTPServer"
alias phpserve="php -S localhost:$1 $2"
alias tl="telnet 127.0.0.1"

alias activate="source .env/bin/activate"

alias rmpyc="find . -name '*.pyc' -exec rm -rf {} \;"
alias rmpyo="find . -name '*.pyo' -exec rm -rf {} \;"
alias rmlog="find . -name '*.log' -exec rm -rf {} \;"
alias rmswp="find . -name '*.swp' -exec rm -rf {} \;"
alias rmmo="find . -name '*.mo' -exec rm -rf {} \;"

alias st='git status'
alias di='git diff'
alias dis='git diff --staged'
alias dit='git diff | tig'
alias dist='git diff --staged | tig'
alias ci='git commit -S'
alias ad='git add'
alias fa='git fetch --all --prune'
alias ga='gitk --all'

alias ll='ls -al'

alias createutfdb="createdb -l en_US.utf8 -E UTF8 -T template0"

alias db_rt3='mysql -upower_user -ppower_user_passwd -hram2.bo'

alias mysql_ram2='mysql -u power_user -ppower_user_passwd -h ram2.bo'

<%- for server in @samba_servers -%>
alias mount_<%= server['name'] %>='sudo mkdir -p <%= server['mountpoint'] %> && sudo mount -t cifs -o uid=sika -o gid=sika <%= server['url'] %> <%= server['mountpoint'] %>'
<%- end -%>

alias vinotes='rm .notes.swp -f; vim notes'
alias vitodo='rm .todo.swp -f; vim todo'
alias viurls='rm .urls.swp -f; vim urls'

alias py=python
alias co=coffee
alias js=nodejs
alias ipy=ipython

alias rfa='echo flushall | redis-cli'

alias cd_pool='cd /home/sika/projects/pool'
alias cd_webpool='cd /home/sika/projects/pool/web-pool'
alias cd_stratum='cd /home/sika/projects/pool/stratum-server'
alias cd_blockchainhub='cd /home/sika/projects/pool/blockchain-hub'
alias cd_poolsrv='cd /home/sika/projects/pool/lib-poolsrv'
alias cd_grit='cd /home/sika/projects/pool/lib-grit'
alias cd_rootsrv='cd /home/sika/projects/pool/root-server'

alias bcl='bitcoin-cli -rpcconnect=chains.bo -rpcport=8332 -rpcuser=btcrpc -rpcpassword=btc '
alias bct='bitcoin-cli -rpcconnect=chains.bo -rpcport=18332 -rpcuser=btcrpc -rpcpassword=btc '
alias bcr='bitcoin-cli -rpcconnect=chains.bo -rpcport=28332 -rpcuser=btcrpc -rpcpassword=btc '
alias ncl='/opt/namecoin/namecoin-cli -rpcconnect=chains.bo -rpcport=8336 -rpcuser=nmcrpc -rpcpassword=nmc '
alias nct='/opt/namecoin/namecoin-cli -rpcconnect=chains.bo -rpcport=18336 -rpcuser=nmcrpc -rpcpassword=nmc '
alias ncr='/opt/namecoin/namecoin-cli -rpcconnect=chains.bo -rpcport=28336 -rpcuser=nmcrpc -rpcpassword=nmc '
alias zcl='/opt/zcash/zcash-cli -rpcconnect=chains.bo -rpcport=8232 -rpcuser=zu -rpcpassword=zp '
alias zct='/opt/zcash/zcash-cli -rpcconnect=chains.bo -rpcport=18232 -rpcuser=zu -rpcpassword=zp '
alias zcr='/opt/zcash/zcash-cli -rpcconnect=chains.bo -rpcport=28232 -rpcuser=zu -rpcpassword=zp '

alias lbe_livenet='/home/sika/projects/lbe/.env/bin/python /home/sika/projects/lbe/lbe.py 0.0.0.0 9001 chains.bo 8332 btcrpc btc'
alias lbe_testnet='/home/sika/projects/lbe/.env/bin/python /home/sika/projects/lbe/lbe.py 0.0.0.0 9002 chains.bo 18332 btcrpc btc'
alias lbe_regtest='/home/sika/projects/lbe/.env/bin/python /home/sika/projects/lbe/lbe.py 0.0.0.0 9003 chains.bo 28332 btcrpc btc'
alias lbe_livenet_nmc='/home/sika/projects/lbe/.env/bin/python /home/sika/projects/lbe/lbe.py 0.0.0.0 9011 chains.bo 8336 nmcrpc nmc'
alias lbe_testnet_nmc='/home/sika/projects/lbe/.env/bin/python /home/sika/projects/lbe/lbe.py 0.0.0.0 9012 chains.bo 18336 nmcrpc nmc'
alias lbe_regtest_nmc='/home/sika/projects/lbe/.env/bin/python /home/sika/projects/lbe/lbe.py 0.0.0.0 9013 chains.bo 28336 nmcrpc nmc'
alias lbe_livenet_zcash='/home/sika/projects/lbe-zcash/.env/bin/python /home/sika/projects/lbe-zcash/lbe.py 0.0.0.0 9021 chains.bo 8232 zu zp'
alias lbe_testnet_zcash='/home/sika/projects/lbe-zcash/.env/bin/python /home/sika/projects/lbe-zcash/lbe.py 0.0.0.0 9022 chains.bo 18232 zu zp'
alias lbe_regtest_zcash='/home/sika/projects/lbe-zcash/.env/bin/python /home/sika/projects/lbe-zcash/lbe.py 0.0.0.0 9023 chains.bo 28232 zu zp'

alias yd='youtube-dl --extract-audio --audio-format mp3 '

alias xrandr_pool='xrandr --auto --output DVI-I-1 --mode 1920x1080 --output DVI-I-2 --mode 1920x1080 --right-of DVI-I-1'
alias i3lock='i3lock -i bg2.png'


alias mc_mol_loc='mc . sh://192.168.1.51/mnt'
alias xrandr_pool='xrandr --auto --output DVI-I-1 --mode 1920x1080 --output DVI-I-2 --mode 1920x1080 --right-of DVI-I-1'


alias settitle='. /etc/bash.settitle'

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.)
    color_prompt=yes
    else
    color_prompt=
    fi
fi

    color_prompt=yes
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    #alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1)\$ '

export NVM_DIR="/home/sika/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm


