#!/bin/bash

# barshrc
# Ondrej Sika <ondrej@ondrejsika.com>
#####################################

ONDREJ_SIKA_DESKTOP_HOSTNAMES=" sika-br sika-home sika-x250 sika-macbookpro sika-macbookpro.local pool-dev "

export EDITOR=/usr/bin/vim

# Git configuration for Ondrej Sika's desktop only (also for SSH forward)
if [[ $ONDREJ_SIKA_DESKTOP_HOSTNAMES =~ " $HOSTNAME " ]]; then
  export GIT_AUTHOR_NAME="Ondrej Sika"
  export GIT_AUTHOR_EMAIL="ondrej@ondrejsika.com"
  export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
  export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
fi

# Set language for MC
export LANG=en_US.UTF-8

# Bash history settings
export HISTCONTROL=ignoreboth
export HISTSIZE=1000000
export HISTFILESIZE=2000000
shopt -s histappend

export PATH=$PATH:/home/sika/bin
# Ruby (on Mac, using Brew)
export PATH=/usr/local/opt/ruby/bin:$PATH

alias cc="xclip -sel clip"

alias serve="python -m SimpleHTTPServer"
alias phpserve="php -S localhost:$1 $2"
alias tl="telnet 127.0.0.1"

alias activate="source .env/bin/activate"

alias rmpyc="find . -name '*.pyc' -exec rm -rf {} \;"
alias rmpyo="find . -name '*.pyo' -exec rm -rf {} \;"
alias rmlog="find . -name '*.log' -exec rm -rf {} \;"
alias rmswp="find . -name '*.swp' -exec rm -rf {} \;"
alias rmmo="find . -name '*.mo' -exec rm -rf {} \;"

alias st='git status'
complete -F _complete_alias st
alias sta='git status --untracked-files=all'
complete -F _complete_alias sta
alias di='git diff'
complete -F _complete_alias di
alias dis='git diff --staged'
complete -F _complete_alias dis
alias dit='git diff | tig'
complete -F _complete_alias dit
alias dist='git diff --staged | tig'
complete -F _complete_alias dist
alias ci='git commit -S'
complete -F _complete_alias ci
alias co='git checkout'
complete -F _complete_alias co
alias br='git branch'
complete -F _complete_alias br
alias ad='git add'
complete -F _complete_alias ad
alias fa='git fetch --all --prune'
complete -F _complete_alias fa
alias ga='gitk --all'
complete -F _complete_alias ga

alias ll='ls -al'

alias createutfdb="createdb -l en_US.utf8 -E UTF8 -T template0"

alias yd='youtube-dl --extract-audio --audio-format mp3 '


# Docker
alias dra="docker ps -a  -q | xargs docker rm -f"

# Terraform
alias tf=terraform
complete -F _complete_alias tf

# Mac Aliases
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac


# BASH debian default config
shopt -s checkwinsize
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
fi


# Support for local bashrc, bash aliases
if [ -z $LOCAL_BASHRC_LOADED ]; then
    if [ -f ~/.bashrc ]; then
        export LOCAL_BASHRC_LOADED=yes
        . ~/.bashrc
    fi
fi

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# VirtualEnv Wrapper
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    export WORKON_HOME=~/.virtualenvs
    mkdir -p $WORKON_HOME
    . /usr/local/bin/virtualenvwrapper.sh 2> /dev/null
fi

# Enable autocomplete
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1)\$ '

# Set red "user@host" prompt on servers
if [[ ! $ONDREJ_SIKA_DESKTOP_HOSTNAMES =~ " $HOSTNAME " ]]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1)\$ '
fi


export NVM_DIR="$HOME/.nvm"

# Linux
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Mac Bash Completion
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# Mac
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
