export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git kube-ps1)
source $ZSH/oh-my-zsh.sh

# Individual history per tab
#
# See: https://superuser.com/a/1248123/675796
unsetopt inc_append_history
unsetopt share_history

# Git

alias st='git status'
alias sta='git status --untracked-files=all'
alias di='git diff'
alias dis='git diff --staged'
alias dit='git diff | tig'
alias dist='git diff --staged | tig'
alias ci='git commit -S'
alias co='git checkout'
alias br='git branch'
alias ad='git add'
alias fa='git fetch --all --prune'
alias ga='gitk --all'

# Kubernetes

alias k=kubectl
alias kx=kubectx
alias kn=kubens

# kube-ps1

function kps1() {
  export KUBE_PS1_SYMBOL_ENABLE=false
  export PS1='$(kube_ps1) '$PS1
}

# Terraform

alias tf=terraform
alias tfi="terraform init"
alias tfa="terraform apply"
alias tfd="terraform destroy"
alias tfp="terraform plan"
alias tfs="terraform show"
alias tfo="terraform output"

# Terrafor autocompletition
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/terraform terraform

# slu
. <(slu completion zsh); compdef _slu slu

# tergum
. <(tergum completion zsh); compdef _tergum tergum

# training-cli
. <(training-cli completion zsh); compdef _training-cli training-cli

# watch
alias watch="watch "
alias w="watch -n 0.3 "

# Fuck
eval $(thefuck --alias)
