export PROMPT="%n@%m%\:%~$ "
export RPROMPT="%(?..%?)"

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git kube-ps1 docker docker-compose)
source $ZSH/oh-my-zsh.sh


# ~/bin

[ -d "${HOME}/bin" ] && export PATH="${HOME}/bin:${PATH}"
[ -d "${HOME}/.yarn/bin" ] && export PATH="${HOME}/.yarn/bin:${PATH}"
[ -d "${HOME}/.local/bin" ] && export PATH="${HOME}/.local/bin:${PATH}"

# Individual history per tab
#
# See: https://superuser.com/a/1248123/675796
unsetopt inc_append_history
unsetopt share_history

# Git

alias st='git status'
alias sta='git status --untracked-files=all'
alias di='git diff'
alias dis='git diff --staged'
alias dit='git diff | tig'
alias dist='git diff --staged | tig'
alias ci='git commit'
alias co='git checkout'
alias sw='git switch'
alias br='git branch'
alias ad='git add'
alias fa='git fetch --all --prune'
alias ga='gitk --all'
alias glo='git log --oneline '

alias guo='slu git url open'

# Kubernetes

alias k=kubectl
alias kx=kubectx
alias kn=kubens

alias kdev="slu kdev "
alias ddev="slu ddev "

# Old aliases without slu
# alias kdev="kubectl run dev-$(date +%s) --rm -ti --image sikalabs/dev -- bash"
# alias ddev="docker run -ti -w $(pwd) -v $(pwd):$(pwd) sikalabs/dev"

# krew

export PATH="${PATH}:${HOME}/.krew/bin"

# kube-ps1

export KPS1_ACTIVE=0
function kps1() {
  [[ "$KPS1_ACTIVE" == "1" ]] && return 0
  export KPS1_ACTIVE=1
  export KUBE_PS1_SYMBOL_ENABLE=false
  export PS1='$(kube_ps1) '$PS1
}

# KUBECONFIG (for autocomple of export environment variable)
export KUBECONFIG=~/.kube/config

# Terraform

alias tf=terraform
alias tfi="terraform init"
alias tfa="terraform apply"
alias tfd="terraform destroy"
alias tfp="terraform plan"
alias tfs="terraform show"
alias tfo="terraform output"

function tfaa() {
    terraform plan
    echo sleep for 10 seconds ...
    sleep 10
    terraform apply -auto-approve
}

# Terrafor autocompletition
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/terraform terraform

# ArgoCD

command -v argocd &> /dev/null && . <(argocd completion zsh); compdef _argocd argocd

alias acd="argocd "

# slu
command -v slu &> /dev/null && . <(slu completion zsh); compdef _slu slu

# sli
command -v sli &> /dev/null && . <(sli completion zsh); compdef _sli sli

# tergum
command -v tergum &> /dev/null && . <(tergum completion zsh); compdef _tergum tergum

# gobble
command -v gobble &> /dev/null && . <(gobble completion zsh); compdef _gobble gobble

# training-cli
command -v training-cli &> /dev/null && . <(training-cli completion zsh); compdef _training-cli training-cli

# kaf
command -v kaf &> /dev/null && . <(kaf completion zsh); compdef _kaf kaf

# watch
alias watch="watch "
alias w="watch -n 0.3 "

alias viddy="viddy "
alias ww="viddy -n 0.3 "

# Fuck
command -v thefuck &> /dev/null && eval $(thefuck --alias)

# NVM (Node Version Manager)
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Terraform Plugin Cache (save plugins in one dir to save space)
export TF_PLUGIN_CACHE_DIR="$HOME/.terraform-plugin-cache"

# Docker
alias dra='docker ps -a -q | xargs -r docker rm -f'
alias docker-compose="docker compose "

# youtube-dl mp3
alias yd='youtube-dl --extract-audio --audio-format mp3 '


# Completion

command -v minikube &> /dev/null &&  . <(minikube completion zsh)

# History
export HISTFILE=~/.zsh_history
export HISTSIZE=999999999
export SAVEHIST=$HISTSIZE

export HISTORY_IGNORE="(MAGICSHIT|*ACCESS_KEY*|*SECRET_KEY*|*TOKEN*)"
